module.exports = {
        'likes': '{ likes, number } me gusta',
        'logout': 'Salir',
        'english': 'Inglés',
        'spanish': 'Español',
        'signup.subheading': 'Regístrate para ver fotos y videos de tus amigos.',
        'signup.facebook': 'Iniciar sesión con Facebook',
        'or': "O",
        'email': 'Correo electrónico',
        'username': 'Nombre de usuario',
        'fullname': 'Nombre completo',
        'password': 'Contraseña',
        'signup.call-to-action': 'Regístrate',
        'signup.have-account': '¿Tienes una cuenta?',
        'signin.username': 'Nombre de Usuario',
        'signin': 'Iniciar sesión',
        'recover': '¿Olvidaste tu Contraseña?',
        'signin.not-have-account': '¿No tienes una cuenta?',
        'signup': 'Regístrate',
        'download': 'Descargar aplicación',
        'language': 'Idioma',
        'search' :'Buscar',
        'comment': 'Agrega un comentario',
        'share' : 'Compartir',
        'upload': 'Subir',
        'cancel': 'Cancelar',
        'get-it': 'Lo Entiendo',
        'alert.title': 'ClonInstagram',
        'alert.text': 'Esta es una capia de instagram, hecha con fines educativos, este sitio no pretende suplantar de ninguna manera al sitio oficial',
      }
